import {
  BedIcon,
  CableCarIcon,
  CoffeeIcon,
  MapPinIcon,
  MountainsIcon,
  PaletteIcon,
  SparkleIcon,
  TennisBallIcon,
  WavesIcon,
  WineIcon,
  BowlFoodIcon,
  ForkKnifeIcon,
  SwimmingPoolIcon,
  PersonSimpleBikeIcon,
  BicycleIcon,
  PersonSimpleTaiChiIcon,
  PersonSimpleSkiIcon,
  BuildingsIcon,
  PersonSimpleSwimIcon,
  LeafIcon,
  TagIcon,
  MapPinAreaIcon,
  GolfIcon,
  PathIcon,
  ScooterIcon,
} from "@phosphor-icons/react";
import { FlowerLotusIcon } from "@phosphor-icons/react/dist/ssr";

export const FEATURE_ICONS = {
  BedIcon,
  CableCarIcon,
  CoffeeIcon,
  MapPinIcon,
  MountainIcon: MountainsIcon,
  PaletteIcon,
  SparkleIcon,
  TennisBallIcon,
  WavesIcon,
  WineIcon,
  BowlFoodIcon,
  ForkKnifeIcon,
  SwimmingPoolIcon,
  FlowerLotusIcon,
  PersonSimpleBikeIcon,
  BicycleIcon,
  PersonSimpleTaiChiIcon,
  PersonSimpleSkiIcon,
  BuildingsIcon,
  PersonSimpleSwimIcon,
  LeafIcon,
  TagIcon,
  MapPinAreaIcon,
  GolfIcon,
  PathIcon,
  ScooterIcon,
} as const;
